---
title: "Work"
format: html
---

From current workplace (unless specified otherwise): IT department at University of Oslo

# Courses and workshops held

[Introduction to R and RStudio](https://www.uio.no/tjenester/it/kurs/alle/dht/r/events/2024-03-rstudio-intro.html)

[Introduction to Machine learning in R: Classification ](https://www.uio.no/tjenester/it/kurs/alle/dht/ml/events/2024-04-ml-r-intro.html)

[Introduction to Machine learning in Python: Classification ](https://www.uio.no/tjenester/it/kurs/alle/dht/ml-python/events/2024-05-ml-python-intro.html)

[Getting started with statistics and programming using GPT UiO](https://www.uio.no/tjenester/it/kurs/alle/dht/gpt-stats-programmering/events/2024-05-gpt-statistics.html)

[Workshop: Getting up-to-speed with Python](https://www.uio.no/dscience/english/news-and-events/events/workshop-getting-up-to-speed-with-python-.html)

# Selected work projects {#sec-work-proj}

[RASK](https://www.antibiotika.no/rask/): Automated HTML reports with R and Quart,o about use of antibiotics nationwide in Norway

[Digikost](https://www.med.uio.no/imb/forskning/om/infrastruktur/kostholdsmetodikk/digikost.html): Automated HTML reports using RMarkdown. Data ingested from UiO Nettskjema in TSD

[MinMat](https://www.med.uio.no/imb/om/aktuelt/aktuelle-saker/2021/bli-med-pa-forskning-pa-kosthold-hos-eldre.html): Wrote R code that parses UiO Nettskjema data in TSD. Data ingested via a mobile app through UiO nettskjema. Later rewrote code to python.

[iTandem](https://www.oslo-universitetssykehus.no/itandem): Wrote R code that parses UiO Nettskjema data in TSD. Data ingested via a mobile app through UiO nettskjema. Later rewrote code to python.

[NORTRAS](https://www.sv.uio.no/psi/forskning/prosjekter/nortras/): Wrote an R Shiny app that vizualises data (graphs and tables) for the NORTRAS study

[MinDag](https://www.med.uio.no/norment/forskning/deltakelse/app-og-aktigrafi/): Wrote an R Shiny app that creates HTML reports based on data delivered from an app (connected to UiO Nettskjema)


# Talks and presentations

{{< video files/ML_lynkurs_IT_konferanse_2021.mp4 width="600" height="350" title="IT konferanse" >}}
Crash course (Norwegian) in how to use tidymodels for building machine learning models.
<br>
From [IT conference at UiO 2021](https://www.uio.no/for-ansatte/enhetssider/arrangement/it-konferansen/2021/)
<br>

{{< video files/NORTRAS_app_data_at_uio_2022.mp4 width="600" height="350" title="NORTRAS demo" >}}
Presented NORTRAS shiny app (Norwegian) with dummy data (see projects section), at [data@UiO 2022](https://www.usit.uio.no/om/arrangementer/data/2022/)


[Talk](files/DMN_R_in_TSD.pdf) at [UiO Data Manager Network](https://www.ub.uio.no/english/libraries/dsc/data-managers-network/) october 2022 about how R is used in production in TSD.
<br>
Mentions some of the projects in [Selected work projects](#sec-work-proj)

[Talk](files/UiO_ConcePTION_Workshop_march_2023.pdf) discussing an outsider (UiO IT) perspective of the [ConcePTION](https://www.imi-conception.eu/) project.
<br>
<br>
{{< video files/R_live_educloud_ondemand.mp4 width="600" height="350" title="R educloud live" >}}
Live coding in R (short notice backup), showcasing [Educloud On Demand](https://www.uio.no/tjenester/it/forskning/beregning/open-on-demand/) (run software on HPC interactively) at [data@UiO 2024](https://www.usit.uio.no/om/arrangementer/data/2024/)

# Scientific articles

From my days as a PhD researcher or in my spare time

## PhD

PhD thesis:
<br> 
[Elucidating depression heterogeneity using clinical, neuroimaging and genetic data](https://www.duo.uio.no/handle/10852/71645)

Article 1: 
<br>
[Data-driven clustering reveals a link between symptoms and functional brain connectivity in depression](https://www.sciencedirect.com/science/article/abs/pii/S2451902218301290)

Article 2: 
<br>
[Brain connectome mapping of complex human traits and their polygenic architecture using machine learning](https://www.sciencedirect.com/science/article/abs/pii/S0006322319317913)

Article 3: 
<br>
[Multimodal fusion of structural and functional brain imaging in depression using linked independent component analysis](https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.24802)



## Selected co-author papers

[Inflammation and cognition in severe mental illness: patterns of covariation and subgroups](https://www.nature.com/articles/s41380-022-01924-w)

[Data-driven health deficit assessment improves a frailty index’s prediction of current cognitive status and future conversion to dementia: results from ADNI](https://link.springer.com/article/10.1007/s11357-022-00669-2)